server:
  port: ${SERVER_PORT:8888}

spring:
  application:
    name: config-server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:git}
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URI:https://github.com/spring-cloud-samples/config-repo}
          default-label: ${CONFIG_GIT_DEFAULT_LABEL:main}
          search-paths: ${CONFIG_GIT_SEARCH_PATHS:}
          clone-on-start: ${CONFIG_GIT_CLONE_ON_START:true}
          skip-ssl-validation: ${CONFIG_GIT_SKIP_SSL_VALIDATION:false}
          force-pull: ${CONFIG_GIT_FORCE_PULL:false}
          username: ${CONFIG_GIT_USERNAME:}
          password: ${CONFIG_GIT_PASSWORD:}

management:
  endpoints:
    web:
      exposure:
        include: health,info
